;;; company-dict-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from company-dict.el

(autoload 'company-dict-refresh "company-dict" "\
Refresh all loaded dictionaries." t)
(autoload 'company-dict "company-dict" "\
`company-mode' backend for user-provided dictionaries. Dictionary files are lazy
loaded.

(fn COMMAND &optional ARG &rest IGNORED)" t)

;;; End of scraped data

(provide 'company-dict-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; company-dict-autoloads.el ends here
