;;; xref-js2-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from xref-js2.el

(autoload 'xref-js2-xref-backend "xref-js2" "\
Xref-Js2 backend for Xref.")

;;; End of scraped data

(provide 'xref-js2-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; xref-js2-autoloads.el ends here
