;;; counsel-css-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from counsel-css.el

(autoload 'counsel-css-imenu-setup "counsel-css" "\
Set up imenu to recognize css/scss/less/stylus selectors.")
(autoload 'counsel-css "counsel-css" "\
Jump to a css selector." t)

;;; End of scraped data

(provide 'counsel-css-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; counsel-css-autoloads.el ends here
