;;; nodejs-repl-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from nodejs-repl.el

(autoload 'nodejs-repl-send-line "nodejs-repl" "\
Send the current line to the `nodejs-repl-process'" t)
(autoload 'nodejs-repl-send-region "nodejs-repl" "\
Send the current region to the `nodejs-repl-process'

(fn START END)" t)
(autoload 'nodejs-repl-send-buffer "nodejs-repl" "\
Send the current buffer to the `nodejs-repl-process'" t)
(autoload 'nodejs-repl-load-file "nodejs-repl" "\
Load the file to the `nodejs-repl-process'

(fn FILE)" t)
(autoload 'nodejs-repl-send-last-expression "nodejs-repl" "\
Send the expression before point to the `nodejs-repl-process'" t)
(autoload 'nodejs-repl-switch-to-repl "nodejs-repl" "\
If there is a `nodejs-repl-process' running switch to it,
otherwise spawn one." t)
(autoload 'nodejs-repl "nodejs-repl" "\
Run Node.js REPL." t)

;;; End of scraped data

(provide 'nodejs-repl-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; nodejs-repl-autoloads.el ends here
