;;; hlinum-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from hlinum.el

(autoload 'hlinum-activate "hlinum" "\
Enable highlighting current line number." t)
(autoload 'hlinum-deactivate "hlinum" "\
Disable highlighting current line number." t)

;;; End of scraped data

(provide 'hlinum-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; hlinum-autoloads.el ends here
