;;; toggle-quotes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from toggle-quotes.el

(autoload 'toggle-quotes "toggle-quotes" "\
Toggle between single quotes and double quotes." t)

;;; End of scraped data

(provide 'toggle-quotes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; toggle-quotes-autoloads.el ends here
