;;; stylus-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from stylus-mode.el

(autoload 'stylus-mode "stylus-mode" "\
Major mode for editing stylus node.js templates

(fn)" t)
(add-to-list 'auto-mode-alist '("\\.styl\\'" . stylus-mode))

;;; End of scraped data

(provide 'stylus-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stylus-mode-autoloads.el ends here
